/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sqlitewrapper_Database */

#ifndef _Included_sqlitewrapper_Database
#define _Included_sqlitewrapper_Database
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sqlitewrapper_Database
 * Method:    openInternal
 * Signature: ([JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_sqlitewrapper_Database_openInternal
  (JNIEnv *, jclass, jlongArray, jstring, jint);

/*
 * Class:     sqlitewrapper_Database
 * Method:    execInternal
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_sqlitewrapper_Database_execInternal
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     sqlitewrapper_Database
 * Method:    closeInternal
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_sqlitewrapper_Database_closeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
